bases: 
  mpi_petsc: 
    defaults:
      mat_common: mat_common
      mat: mat_petsc
      vec_common: vec_common
      vec: vec_petsc
      solver_common: solver_common
      solver: solver_petsc
      parallel_env: parallel_env_mpi_petsc
      parallel_env_error: parallel_errors_mpi_petsc
      parallel_utils: parallel_utils_mpi
      fv_common: fv_common
      fv: fv_discretisation
      read_config: read_config_yaml
      io: io_adios2
      io_setup: io_setup_adios2
      io_visualisation: io_visualisation_adios2
      io_visualisation_common: io_visualisation_common
      meshing: meshing_accessors
      meshing_ops: meshing_operators
      pv_coupling: pv_coupling_simple
      timestepping: timestepping_second_order
      partitioning: partitioning_parhip
      partitioning_common: partitioning_common
      poisson_discretisation: poisson_discretisation_ref
    options:
      timestepping: [timestepping_first_order, timestepping_second_order]
      poisson_discretisation: [poisson_discretisation_ref, poisson_discretisation_acc, poisson_discretisation_omp, poisson_discretisation_bindc]
  mpi:
    defaults:
      mat_common: mat_common
      mat: mat_petsc
      vec_common: vec_common
      vec: vec_petsc
      solver_common: solver_common
      solver: solver_petsc
      parallel_env: parallel_env_mpi
      parallel_env_error: parallel_errors_mpi
      parallel_utils: parallel_utils_mpi
      fv_common: fv_common
      fv: fv_discretisation
      read_config: read_config_yaml
      io: io_adios2
      io_setup: io_setup_adios2
      io_visualisation: io_visualisation_adios2
      io_visualisation_common: io_visualisation_common
      meshing: meshing_accessors
      meshing_ops: meshing_operators
      pv_coupling: pv_coupling_simple
      timestepping: timestepping_second_order
      partitioning: partitioning_parhip
      partitioning_common: partitioning_common
      poisson_discretisation: poisson_discretisation_ref
    options:
      timestepping: [timestepping_first_order, timestepping_second_order]
      poisson_discretisation: [poisson_discretisation_ref, poisson_discretisation_acc, poisson_discretisation_omp, poisson_discretisation_bindc]
