#!/bin/bash

code=$1
error_path=$CCS_DIR/src/ccs_core/error_codes.f90

if [ -n "$code" ] && [ "$code" -ne 0 ]
then
    message=$(grep \ $code $error_path | sed 's/^.*::\ \(.*\)$/\1/;s/=\s*[0-9]*\s*//;s/_/ /g')
    echo ERROR $code: "$message"
fi

