!> Test that partitions a square mesh generated by CCS

program test_mesh_partitioning_parhip

  use testing_lib
  use partitioning, only: compute_partitioner_input, &
                          partition_kway, compute_connectivity
  use kinds, only: ccs_int, ccs_long
  use types, only: topology
  use mesh_utils, only : build_square_mesh

  implicit none

  type(topology) :: topo
  type(ccs_mesh), target :: mesh
  integer :: i, j, k, n, current, previous

  call init()

  ! Create a square mesh
  print *, "Building mesh"
  mesh = build_square_mesh(par_env, 4, 1.0_ccs_real)

  topo%global_num_cells = mesh%nglobal
  topo%local_num_cells = mesh%nlocal
  
  allocate(topo%global_partition(topo%global_num_cells))
  allocate(topo%local_partition(topo%local_num_cells))

  n = count(mesh%neighbour_indices > 0)

  allocate(topo%adjncy(n))
  allocate(topo%adjwgt(n))

  k = 1
  do i = 1, size(mesh%neighbour_indices)
    if(mesh%neighbour_indices(i) > 0) then
      topo%adjncy(k) = mesh%neighbour_indices(i)
      k = k + 1
    end if
  end do

  j = 1
  topo%xadj(j) = 1
  previous = topo%adjncy(1)

  do i = 2, size(topo%adjncy)
    current = topo%adjncy(i)
    if (current < previous) then
      j = j + 1
      topo%xadj(j) = i 
    end if
    previous = current
  end do

  topo%xadj(j + 1) = size(topo%adjncy) + 1

  ! Hardcode for now
  allocate(topo%vtxdist(5))
  topo%vtxdist = (/ 1, 5, 9, 13, 17 /)

  topo%adjwgt = 1
  topo%vwgt = 1

  print*, "Inital global partition:"
  if(par_env%proc_id == 0) then
    do i=1,15
      print*, topo%global_partition(i)
    end do
  end if

  call partition_kway(par_env, topo)

  print*, "Global partition after partitioning:"
  if(par_env%proc_id == 0) then
    do i=1,15
      print*, topo%global_partition(i)
    end do
  end if

  if(allocated(topo%xadj)) then
    deallocate(topo%xadj)
  end if

  if(allocated(topo%adjncy)) then
    deallocate(topo%adjncy)
  end if

  if(allocated(topo%adjwgt)) then
    deallocate(topo%adjwgt)
  end if

  if(allocated(topo%vwgt)) then
    deallocate(topo%vwgt)
  end if

  if(allocated(topo%vtxdist)) then
    deallocate(topo%vtxdist)
  end if

  call fin()

end program