!> Test that partitions a square mesh generated by CCS

program test_partition_square_mesh

  use testing_lib
  use partitioning, only: compute_partitioner_input, &
                          partition_kway, compute_connectivity
  use kinds, only: ccs_int, ccs_long
  use types, only: topology
  use mesh_utils, only : build_square_mesh

  implicit none

  type(topology) :: topo
  type(ccs_mesh), target :: mesh
  integer :: i, j, k, n

  integer, parameter :: topo_idx_type = kind(topo%adjncy(1))
  integer(topo_idx_type) :: current, previous
  
  call init()

  ! Create a square mesh
  print *, "Building mesh"
  mesh = build_square_mesh(par_env, 4, 1.0_ccs_real)

  ! Assign corresponding mesh values to the topology object
  topo%global_num_cells = mesh%nglobal
  topo%local_num_cells = mesh%nlocal
  topo%halo_num_cells = mesh%nhalo
  topo%total_num_cells = mesh%ntotal
  topo%num_faces = mesh%nfaces_local
  topo%global_indices = mesh%global_indices
  topo%max_faces = mesh%nnb(1)
  topo%global_num_faces = 40 ! Hardcoded for now
  
  allocate(topo%global_partition(topo%global_num_cells))
  allocate(topo%local_partition(topo%local_num_cells))
  allocate(topo%xadj(topo%local_num_cells + 1))
  allocate(topo%face_cell1(topo%global_num_faces))
  allocate(topo%face_cell2(topo%global_num_faces))

  ! Hardcode for now
  topo%face_cell1 = (/ 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, &
                       5, 5, 5, 6,  6, 7,  7, 8,  8, &
                       9,  9,  9, 10, 10, 11, 11, 12, 12, &
                       13, 13, 13, 14, 14, 15, 15, 16, 16 /)
  topo%face_cell2 = (/ 0, 2, 0, 5, 3, 0, 6, 4, 0, 7, 0, 0, 8, & 
                       0, 6, 9, 7, 10, 8, 11, 0, 12, 0, &
                       10, 13, 11, 14, 12, 15,  0, 16, &
                       0, 14,  0, 15,  0, 16,  0,  0,  0/)

  n = count(mesh%neighbour_indices > 0)

  print*,"Number of positive value neighbour indices: ", n

  select type(par_env)
  type is (parallel_environment_mpi)

    ! Also hardcode the adjncy arrays
    if(par_env%num_procs == 4) then

      if(par_env%proc_id == 0) then
        topo%adjncy = (/ 2, 5, 1, 3, 6, 2, 4, 7, 3, 8 /)
      else if (par_env%proc_id == 1) then
        topo%adjncy = (/ 1, 6, 9, 2, 5, 7, 10, 3, 6, 8, 11, 4, 7, 12 /)
      else if (par_env%proc_id == 2) then
        topo%adjncy = (/ 5, 10, 13, 6, 9, 11, 14, 7, 10, 12, 15, 8, 11, 16 /)
      else 
        topo%adjncy = (/ 9, 14, 10, 13, 15, 11, 14, 16, 12, 15 /)
      end if

    else
      print*,"Test must be run on 4 MPI ranks"
    end if 
 
    class default
    write(message, *) "ERROR: Unknown parallel environment!"
    call stop_test(message)
  end select

  print*,"Adjacency arrays: ", topo%adjncy

  ! Now compute the adjacency index array
  j = 1
  topo%xadj(j) = 1
  previous = topo%adjncy(1)

  do i = 2, size(topo%adjncy)
    current = topo%adjncy(i)
    if (current < previous) then
      j = j + 1
      topo%xadj(j) = i 
    end if
    previous = current
  end do

  topo%xadj(j + 1) = size(topo%adjncy) + 1

  print*,"Adjacency index array: ", topo%xadj

  ! Hardcode vtxdist for now
  allocate(topo%vtxdist(5))
  topo%vtxdist = (/ 1, 5, 9, 13, 17 /)

  ! These need to be set to 1 for them to do nothing
  topo%adjwgt = 1
  topo%vwgt = 1

  !call partition_kway(par_env, topo)

  if(par_env%proc_id == 0) then
    print*, "Global partition after partitioning:"
    do i=1,15
      print*, topo%global_partition(i)
    end do
  end if

  ! Compute new connectivity after partitioning
  call compute_connectivity(par_env, topo)

  if(allocated(topo%xadj)) then
    deallocate(topo%xadj)
  end if

  if(allocated(topo%adjncy)) then
    deallocate(topo%adjncy)
  end if

  if(allocated(topo%adjwgt)) then
    deallocate(topo%adjwgt)
  end if

  if(allocated(topo%vwgt)) then
    deallocate(topo%vwgt)
  end if

  if(allocated(topo%vtxdist)) then
    deallocate(topo%vtxdist)
  end if

  call fin()

end program
