FC = mpiifort -fc=ifx
FFLAGS = -cpp -fPIC -stand f18
ifeq ($(VERBOSE),yes)
  FFLAGS += -DVERBOSE
endif
ifeq ($(BUILD),debug)
  # Add debugging (i.e. expensive) flags
  FFLAGS += -g
else
  FFLAGS += -O3
endif
FFLAGS += -xHOST
FFLAGS += -warn all,noexternals
FFLAGS += -module $(OBJ_DIR)
FFLAGS += -no-wrap-margin
CAFFLAGS = -coarray
MPIRUN = mpirun
