CC = cc
CFLAGS = -O3

FC = ftn
FFLAGS = -ef -eF -M969
$(OBJ_DIR)/parallel_env_mpi_petsc.o: FFLAGS+=-hipa0
ifeq ($(VERBOSE),yes)
  FFLAGS += -DVERBOSE
endif
ifeq ($(BUILD),debug)
  # Add debugging (i.e. expensive) flags
  CFLAGS = -O0
  FFLAGS += -G0
  FFLAGS += -g
  FFLAGS += -R bcdps
  FFLAGS += -O0
  FFLAGS += -en
else
endif
ifeq ($(PROFILE),yes)
  FFLAGS += -hlist=msx 
endif
FFLAGS += -homp
FFLAGS += -J$(OBJ_DIR)
CAFFLAGS = -hcaf
MPIRUN = srun --oversubscribe
