!> Reference values generated by generate_distorted_refs.py.
!> Do not edit this file by hand; update the generator instead.
!> SymPy is used only by the generator for exact algebra and printing.
module distorted_refs
  use kinds, only: ccs_real
  implicit none
  public

  integer, parameter :: case_base = 1
  integer, parameter :: case_skew = 2
  integer, parameter :: case_nonorth = 3
  integer, parameter :: case_uneven = 4
  integer, parameter :: case_all = 5
  integer, parameter :: field_lin = 1
  integer, parameter :: field_quad = 2
  integer, parameter :: field_trig = 3
  integer, parameter :: n_cases = 5
  integer, parameter :: n_fields = 3

  ! Non-unit material and flow values make interpolation mistakes visible.
  real(ccs_real), parameter, dimension(n_cases) :: area = [ &
        7.29999999999999982e-01_ccs_real, &
        7.29999999999999982e-01_ccs_real, &
        7.29999999999999982e-01_ccs_real, &
        7.29999999999999982e-01_ccs_real, &
        7.29999999999999982e-01_ccs_real]
  real(ccs_real), parameter, dimension(n_cases) :: schmidt = [ &
        7.39999999999999991e-01_ccs_real, &
        7.39999999999999991e-01_ccs_real, &
        7.39999999999999991e-01_ccs_real, &
        7.39999999999999991e-01_ccs_real, &
        7.39999999999999991e-01_ccs_real]
  real(ccs_real), parameter, dimension(n_cases) :: mflux = [ &
        3.69999999999999996e-01_ccs_real, &
        3.69999999999999996e-01_ccs_real, &
        3.69999999999999996e-01_ccs_real, &
        3.69999999999999996e-01_ccs_real, &
        3.69999999999999996e-01_ccs_real]
  real(ccs_real), parameter, dimension(n_cases) :: lf = [ &
        5.00000000000000000e-01_ccs_real, &
        5.00000000000000000e-01_ccs_real, &
        5.00000000000000000e-01_ccs_real, &
        6.66666666666666630e-01_ccs_real, &
        6.66666666666666630e-01_ccs_real]
  real(ccs_real), parameter, dimension(n_cases) :: dx_mag = [ &
        1.00000000000000000e+00_ccs_real, &
        1.00000000000000000e+00_ccs_real, &
        1.00000000000000000e+00_ccs_real, &
        1.19999999999999996e+00_ccs_real, &
        1.19999999999999996e+00_ccs_real]
  real(ccs_real), parameter, dimension(n_cases) :: dx_orth = [ &
        5.00000000000000000e-01_ccs_real, &
        5.00000000000000000e-01_ccs_real, &
        3.92232270276368089e-01_ccs_real, &
        4.00000000000000022e-01_ccs_real, &
        4.59472088038031135e-01_ccs_real]
  real(ccs_real), parameter, dimension(n_cases) :: dx_face = [ &
        1.00000000000000000e+00_ccs_real, &
        1.00000000000000000e+00_ccs_real, &
        7.84464540552736178e-01_ccs_real, &
        8.00000000000000044e-01_ccs_real, &
        9.18944176076062269e-01_ccs_real]
  real(ccs_real), parameter, dimension(n_cases) :: gamma_f = [ &
        1.48319050758075144e+00_ccs_real, &
        1.48319050758075144e+00_ccs_real, &
        1.48319050758075144e+00_ccs_real, &
        1.62620247366010084e+00_ccs_real, &
        1.62620247366010084e+00_ccs_real]
  real(ccs_real), parameter, dimension(n_cases) :: diff_plain = [ &
        1.08272907053394851e+00_ccs_real, &
        1.08272907053394851e+00_ccs_real, &
        1.08272907053394851e+00_ccs_real, &
        9.89273171476561353e-01_ccs_real, &
        9.89273171476561353e-01_ccs_real]
  real(ccs_real), parameter, dimension(n_cases) :: diff_corr = [ &
        1.08272907053394851e+00_ccs_real, &
        1.08272907053394851e+00_ccs_real, &
        1.38021416464669566e+00_ccs_real, &
        1.48390975721484186e+00_ccs_real, &
        1.29183886973523121e+00_ccs_real]
  real(ccs_real), parameter, dimension(n_cases) :: adv_flux = [ &
        2.70100000000000007e-01_ccs_real, &
        2.70100000000000007e-01_ccs_real, &
        2.70100000000000007e-01_ccs_real, &
        2.70100000000000007e-01_ccs_real, &
        2.70100000000000007e-01_ccs_real]
  real(ccs_real), parameter, dimension(n_cases) :: vol_f = [ &
        4.00000000000000022e-01_ccs_real, &
        4.00000000000000022e-01_ccs_real, &
        4.00000000000000022e-01_ccs_real, &
        3.63333333333333341e-01_ccs_real, &
        3.63333333333333341e-01_ccs_real]
  real(ccs_real), parameter, dimension(n_cases) :: inv_a_f = [ &
        1.02499999999999991e+00_ccs_real, &
        1.02499999999999991e+00_ccs_real, &
        1.02499999999999991e+00_ccs_real, &
        1.08333333333333326e+00_ccs_real, &
        1.08333333333333326e+00_ccs_real]
  real(ccs_real), parameter, dimension(n_cases) :: pc_coeff = [ &
        2.99300000000000010e-01_ccs_real, &
        2.99300000000000010e-01_ccs_real, &
        3.81534135104580119e-01_ccs_real, &
        3.59170138888888879e-01_ccs_real, &
        3.12680703128290882e-01_ccs_real]

  ! Geometry for the owner cell, neighbour cell, and shared face.
  real(ccs_real), parameter, dimension(3, n_cases) :: xp = reshape([ &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real], [3, n_cases])
  real(ccs_real), parameter, dimension(3, n_cases) :: xn = reshape([ &
        1.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        1.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        1.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        1.19999999999999996e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        1.19999999999999996e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real], [3, n_cases])
  real(ccs_real), parameter, dimension(3, n_cases) :: xf = reshape([ &
        5.00000000000000000e-01_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        5.00000000000000000e-01_ccs_real, &
        2.00000000000000011e-01_ccs_real, &
        1.42857142857142849e-01_ccs_real, &
        5.00000000000000000e-01_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        4.00000000000000022e-01_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        4.00000000000000022e-01_ccs_real, &
        2.00000000000000011e-01_ccs_real, &
        1.42857142857142849e-01_ccs_real], [3, n_cases])
  real(ccs_real), parameter, dimension(3, n_cases) :: normal = reshape([ &
        1.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        1.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        7.84464540552736178e-01_ccs_real, &
        5.88348405414552134e-01_ccs_real, &
        1.96116135138184045e-01_ccs_real, &
        1.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        7.84464540552736178e-01_ccs_real, &
        5.88348405414552134e-01_ccs_real, &
        1.96116135138184045e-01_ccs_real], [3, n_cases])
  real(ccs_real), parameter, dimension(2, n_cases) :: volume = reshape([ &
        4.00000000000000022e-01_ccs_real, &
        4.00000000000000022e-01_ccs_real, &
        4.00000000000000022e-01_ccs_real, &
        4.00000000000000022e-01_ccs_real, &
        4.00000000000000022e-01_ccs_real, &
        4.00000000000000022e-01_ccs_real, &
        3.09999999999999998e-01_ccs_real, &
        4.69999999999999973e-01_ccs_real, &
        3.09999999999999998e-01_ccs_real, &
        4.69999999999999973e-01_ccs_real], [2, n_cases])
  real(ccs_real), parameter, dimension(2, n_cases) :: mu = reshape([ &
        1.30000000000000004e+00_ccs_real, &
        9.49999999999999956e-01_ccs_real, &
        1.30000000000000004e+00_ccs_real, &
        9.49999999999999956e-01_ccs_real, &
        1.30000000000000004e+00_ccs_real, &
        9.49999999999999956e-01_ccs_real, &
        1.30000000000000004e+00_ccs_real, &
        9.49999999999999956e-01_ccs_real, &
        1.30000000000000004e+00_ccs_real, &
        9.49999999999999956e-01_ccs_real], [2, n_cases])
  real(ccs_real), parameter, dimension(2, n_cases) :: rho = reshape([ &
        9.00000000000000022e-01_ccs_real, &
        1.14999999999999991e+00_ccs_real, &
        9.00000000000000022e-01_ccs_real, &
        1.14999999999999991e+00_ccs_real, &
        9.00000000000000022e-01_ccs_real, &
        1.14999999999999991e+00_ccs_real, &
        9.00000000000000022e-01_ccs_real, &
        1.14999999999999991e+00_ccs_real, &
        9.00000000000000022e-01_ccs_real, &
        1.14999999999999991e+00_ccs_real], [2, n_cases])
  real(ccs_real), parameter, dimension(2, n_cases) :: inv_a = reshape([ &
        1.19999999999999996e+00_ccs_real, &
        8.49999999999999978e-01_ccs_real, &
        1.19999999999999996e+00_ccs_real, &
        8.49999999999999978e-01_ccs_real, &
        1.19999999999999996e+00_ccs_real, &
        8.49999999999999978e-01_ccs_real, &
        1.19999999999999996e+00_ccs_real, &
        8.49999999999999978e-01_ccs_real, &
        1.19999999999999996e+00_ccs_real, &
        8.49999999999999978e-01_ccs_real], [2, n_cases])
  real(ccs_real), parameter, dimension(3, n_cases) :: xp_orth = reshape([ &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        2.00000000000000011e-01_ccs_real, &
        1.42857142857142849e-01_ccs_real, &
        1.92307692307692318e-01_ccs_real, &
        -2.30769230769230782e-01_ccs_real, &
        -7.69230769230769273e-02_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        3.95604395604395587e-02_ccs_real, &
        -7.03296703296703296e-02_ccs_real, &
        5.27472527472527472e-02_ccs_real], [3, n_cases])
  real(ccs_real), parameter, dimension(3, n_cases) :: xn_orth = reshape([ &
        1.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        1.00000000000000000e+00_ccs_real, &
        2.00000000000000011e-01_ccs_real, &
        1.42857142857142849e-01_ccs_real, &
        8.07692307692307709e-01_ccs_real, &
        2.30769230769230782e-01_ccs_real, &
        7.69230769230769273e-02_ccs_real, &
        8.00000000000000044e-01_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        7.60439560439560402e-01_ccs_real, &
        4.70329670329670324e-01_ccs_real, &
        2.32967032967032972e-01_ccs_real], [3, n_cases])
  real(ccs_real), parameter, dimension(3, 2, n_cases) :: rvec = reshape([ &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        2.00000000000000011e-01_ccs_real, &
        1.42857142857142849e-01_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        2.00000000000000011e-01_ccs_real, &
        1.42857142857142849e-01_ccs_real, &
        1.92307692307692318e-01_ccs_real, &
        -2.30769230769230782e-01_ccs_real, &
        -7.69230769230769273e-02_ccs_real, &
        -1.92307692307692318e-01_ccs_real, &
        2.30769230769230782e-01_ccs_real, &
        7.69230769230769273e-02_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        -4.00000000000000022e-01_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        3.95604395604395587e-02_ccs_real, &
        -7.03296703296703296e-02_ccs_real, &
        5.27472527472527472e-02_ccs_real, &
        -4.39560439560439553e-01_ccs_real, &
        4.70329670329670324e-01_ccs_real, &
        2.32967032967032972e-01_ccs_real], [3, 2, n_cases])

  ! Kernel explicit terms and assembled residual references.
  real(ccs_real), parameter, dimension(n_fields, n_cases) :: diff_exp = &
        reshape([0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        -6.18702326019399187e-02_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        4.71396222387025277e-01_ccs_real, &
        4.23619578226178128e-01_ccs_real, &
        3.94693613182639624e-01_ccs_real, &
        4.15494732020155744e-01_ccs_real, &
        6.29177737059092967e-01_ccs_real, &
        1.92078371005384274e-01_ccs_real, &
        5.42685893541081543e-01_ccs_real, &
        4.90898770499387849e-01_ccs_real, &
        2.12891933846533710e-01_ccs_real], [n_fields, n_cases])
  real(ccs_real), parameter, dimension(n_fields, n_cases) :: cd_face = &
        reshape([1.35000000000000009e+00_ccs_real, &
        1.42500000000000004e+00_ccs_real, &
        9.99679368558885950e-01_ccs_real, &
        1.35000000000000009e+00_ccs_real, &
        1.42500000000000004e+00_ccs_real, &
        9.99679368558885950e-01_ccs_real, &
        1.35000000000000009e+00_ccs_real, &
        1.42500000000000004e+00_ccs_real, &
        9.99679368558885950e-01_ccs_real, &
        1.28000000000000003e+00_ccs_real, &
        1.35200000000000009e+00_ccs_real, &
        8.83685505431717866e-01_ccs_real, &
        1.28000000000000003e+00_ccs_real, &
        1.35200000000000009e+00_ccs_real, &
        8.83685505431717866e-01_ccs_real], [n_fields, n_cases])
  real(ccs_real), parameter, dimension(n_fields, n_cases) :: corr_face = &
        reshape([1.35000000000000009e+00_ccs_real, &
        1.42500000000000004e+00_ccs_real, &
        9.99679368558885950e-01_ccs_real, &
        1.32857142857142851e+00_ccs_real, &
        1.43214285714285716e+00_ccs_real, &
        1.01463933357598024e+00_ccs_real, &
        1.35000000000000009e+00_ccs_real, &
        1.44230769230769229e+00_ccs_real, &
        1.05002540467410710e+00_ccs_real, &
        1.28000000000000003e+00_ccs_real, &
        1.31600000000000006e+00_ccs_real, &
        9.77474556856727905e-01_ccs_real, &
        1.25857142857142867e+00_ccs_real, &
        1.38661538461538458e+00_ccs_real, &
        1.00674740407751706e+00_ccs_real], [n_fields, n_cases])
  real(ccs_real), parameter, dimension(n_fields, n_cases) :: cd_exp = &
        reshape([9.45349999999999940e-02_ccs_real, &
        1.14792500000000006e-01_ccs_real, &
        1.16956730781088439e-01_ccs_real, &
        9.45349999999999940e-02_ccs_real, &
        1.14792500000000006e-01_ccs_real, &
        1.16956730781088439e-01_ccs_real, &
        9.45349999999999940e-02_ccs_real, &
        1.14792500000000006e-01_ccs_real, &
        1.16956730781088439e-01_ccs_real, &
        7.56280000000000008e-02_ccs_real, &
        9.50751999999999986e-02_ccs_real, &
        8.56267883504403249e-02_ccs_real, &
        7.56280000000000008e-02_ccs_real, &
        9.50751999999999986e-02_ccs_real, &
        8.56267883504403249e-02_ccs_real], [n_fields, n_cases])
  real(ccs_real), parameter, dimension(n_fields, n_cases) :: upwind_exp = &
        reshape([0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real], [n_fields, n_cases])
  real(ccs_real), parameter, dimension(n_fields, n_cases) :: luds_exp = &
        reshape([0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        -5.78785714285714320e-03_ccs_real, &
        -5.78785714285714320e-03_ccs_real, &
        4.04068655111715792e-03_ccs_real, &
        4.61247692307692331e-02_ccs_real, &
        4.61247692307692331e-02_ccs_real, &
        5.22181031221294265e-02_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        1.31310153846153840e-02_ccs_real, &
        1.31310153846153840e-02_ccs_real, &
        1.26815393296600028e-02_ccs_real], [n_fields, n_cases])
  real(ccs_real), parameter, dimension(n_fields, n_cases) :: face_corr = &
        reshape([0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        -2.14285714285714288e-02_ccs_real, &
        7.14285714285714263e-03_ccs_real, &
        1.49599650170942535e-02_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        1.73076923076923087e-02_ccs_real, &
        5.03460361152210448e-02_ccs_real, &
        -1.40000000000000013e-01_ccs_real, &
        -2.11999999999999994e-01_ccs_real, &
        -6.47203679575155538e-02_ccs_real, &
        -1.61428571428571421e-01_ccs_real, &
        -1.41384615384615386e-01_ccs_real, &
        -3.54475207367263984e-02_ccs_real], [n_fields, n_cases])
  real(ccs_real), parameter, dimension(n_fields, n_cases) :: mom_adv_res = &
        reshape([-3.64634999999999987e-01_ccs_real, &
        -3.84892500000000026e-01_ccs_real, &
        -2.70013397447755099e-01_ccs_real, &
        -3.58847142857142865e-01_ccs_real, &
        -3.86821785714285715e-01_ccs_real, &
        -2.74054083998872267e-01_ccs_real, &
        -3.64634999999999987e-01_ccs_real, &
        -3.89567307692307685e-01_ccs_real, &
        -2.83611861802476328e-01_ccs_real, &
        -3.07914000000000021e-01_ccs_real, &
        -3.07914000000000021e-01_ccs_real, &
        -2.21202483631782049e-01_ccs_real, &
        -3.02126142857142843e-01_ccs_real, &
        -3.26987215384615393e-01_ccs_real, &
        -2.29109079666117182e-01_ccs_real], [n_fields, n_cases])
  real(ccs_real), parameter, dimension(n_fields, n_cases) :: mom_diff_res &
        = reshape([7.57910349373764003e-01_ccs_real, &
        9.20319709953856258e-01_ccs_real, &
        9.37670880498312820e-01_ccs_real, &
        7.57910349373764003e-01_ccs_real, &
        9.82189942555796169e-01_ccs_real, &
        9.37670880498312820e-01_ccs_real, &
        4.94753692865661676e-01_ccs_real, &
        7.49562461723513151e-01_ccs_real, &
        8.00606916064516616e-01_ccs_real, &
        8.30989464040311487e-01_ccs_real, &
        9.37830966559780155e-01_ccs_real, &
        1.21920367318775047e+00_ccs_real, &
        5.42458757036512695e-01_ccs_real, &
        8.73283075941016285e-01_ccs_real, &
        1.01571984121852399e+00_ccs_real], [n_fields, n_cases])
  real(ccs_real), parameter, dimension(n_fields, n_cases) :: mom_res = &
        reshape([3.93275349373764016e-01_ccs_real, &
        5.35427209953856287e-01_ccs_real, &
        6.67657483050557721e-01_ccs_real, &
        3.99063206516621138e-01_ccs_real, &
        5.95368156841510454e-01_ccs_real, &
        6.63616796499440498e-01_ccs_real, &
        1.30118692865661661e-01_ccs_real, &
        3.59995154031205467e-01_ccs_real, &
        5.16995054262040399e-01_ccs_real, &
        5.23075464040311466e-01_ccs_real, &
        6.29916966559780134e-01_ccs_real, &
        9.98001189555968393e-01_ccs_real, &
        2.40332614179369797e-01_ccs_real, &
        5.46295860556400892e-01_ccs_real, &
        7.86610761552406723e-01_ccs_real], [n_fields, n_cases])
  real(ccs_real), parameter, dimension(n_fields, n_cases) :: pc_res = &
        reshape([2.09510000000000002e-01_ccs_real, &
        2.54404999999999992e-01_ccs_real, &
        2.59201403352682491e-01_ccs_real, &
        2.09510000000000002e-01_ccs_real, &
        2.37302142857142850e-01_ccs_real, &
        2.59201403352682491e-01_ccs_real, &
        3.97382476101231896e-01_ccs_real, &
        4.41405645536375790e-01_ccs_real, &
        4.39523847452026717e-01_ccs_real, &
        4.02270555555555576e-01_ccs_real, &
        5.31571805555555610e-01_ccs_real, &
        3.88082348145394829e-01_ccs_real, &
        3.94005174355108345e-01_ccs_real, &
        4.49009489692225705e-01_ccs_real, &
        3.48906046894915778e-01_ccs_real], [n_fields, n_cases])
  real(ccs_real), parameter, dimension(n_fields, n_cases) :: rc_flux = &
        reshape([0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        -9.03496889981966755e-03_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        -8.20000000000000069e-03_ccs_real, &
        -9.03496889981966755e-03_ccs_real, &
        2.45243226990299129e-01_ccs_real, &
        2.28759665831934772e-01_ccs_real, &
        6.93380265340920593e-02_ccs_real, &
        1.57444444444444442e-01_ccs_real, &
        1.33827777777777768e-01_ccs_real, &
        3.65666772796779949e-02_ccs_real, &
        2.45230537904319673e-01_ccs_real, &
        2.02631028110667938e-01_ccs_real, &
        4.45122710288099327e-02_ccs_real], [n_fields, n_cases])

  ! Sampled values and exact gradients for the analytic fields.
  real(ccs_real), parameter, dimension(2, n_fields, n_cases) :: phi_val = &
        reshape([1.00000000000000000e+00_ccs_real, &
        1.69999999999999996e+00_ccs_real, &
        1.00000000000000000e+00_ccs_real, &
        1.85000000000000009e+00_ccs_real, &
        5.66666666666666652e-01_ccs_real, &
        1.43269207045110525e+00_ccs_real, &
        1.00000000000000000e+00_ccs_real, &
        1.69999999999999996e+00_ccs_real, &
        1.00000000000000000e+00_ccs_real, &
        1.85000000000000009e+00_ccs_real, &
        5.66666666666666652e-01_ccs_real, &
        1.43269207045110525e+00_ccs_real, &
        1.00000000000000000e+00_ccs_real, &
        1.69999999999999996e+00_ccs_real, &
        1.00000000000000000e+00_ccs_real, &
        1.85000000000000009e+00_ccs_real, &
        5.66666666666666652e-01_ccs_real, &
        1.43269207045110525e+00_ccs_real, &
        1.00000000000000000e+00_ccs_real, &
        1.84000000000000008e+00_ccs_real, &
        1.00000000000000000e+00_ccs_real, &
        2.05600000000000005e+00_ccs_real, &
        5.66666666666666652e-01_ccs_real, &
        1.51772318296182029e+00_ccs_real, &
        1.00000000000000000e+00_ccs_real, &
        1.84000000000000008e+00_ccs_real, &
        1.00000000000000000e+00_ccs_real, &
        2.05600000000000005e+00_ccs_real, &
        5.66666666666666652e-01_ccs_real, &
        1.51772318296182029e+00_ccs_real], [2, n_fields, n_cases])
  real(ccs_real), parameter, dimension(2, n_fields, n_cases) :: pressure = &
        reshape([2.50000000000000000e-01_ccs_real, &
        1.05000000000000004e+00_ccs_real, &
        2.50000000000000000e-01_ccs_real, &
        1.00000000000000000e+00_ccs_real, &
        4.83333333333333337e-01_ccs_real, &
        9.07597402045261847e-01_ccs_real, &
        2.50000000000000000e-01_ccs_real, &
        1.05000000000000004e+00_ccs_real, &
        2.50000000000000000e-01_ccs_real, &
        1.00000000000000000e+00_ccs_real, &
        4.83333333333333337e-01_ccs_real, &
        9.07597402045261847e-01_ccs_real, &
        2.50000000000000000e-01_ccs_real, &
        1.05000000000000004e+00_ccs_real, &
        2.50000000000000000e-01_ccs_real, &
        1.00000000000000000e+00_ccs_real, &
        4.83333333333333337e-01_ccs_real, &
        9.07597402045261847e-01_ccs_real, &
        2.50000000000000000e-01_ccs_real, &
        1.20999999999999996e+00_ccs_real, &
        2.50000000000000000e-01_ccs_real, &
        1.13799999999999990e+00_ccs_real, &
        4.83333333333333337e-01_ccs_real, &
        9.68743529958301819e-01_ccs_real, &
        2.50000000000000000e-01_ccs_real, &
        1.20999999999999996e+00_ccs_real, &
        2.50000000000000000e-01_ccs_real, &
        1.13799999999999990e+00_ccs_real, &
        4.83333333333333337e-01_ccs_real, &
        9.68743529958301819e-01_ccs_real], [2, n_fields, n_cases])
  real(ccs_real), parameter, dimension(3, 2, n_fields, n_cases) :: &
        grad_phi = reshape([6.99999999999999956e-01_ccs_real, &
        -2.00000000000000011e-01_ccs_real, &
        1.30000000000000004e-01_ccs_real, &
        6.99999999999999956e-01_ccs_real, &
        -2.00000000000000011e-01_ccs_real, &
        1.30000000000000004e-01_ccs_real, &
        6.99999999999999956e-01_ccs_real, &
        -2.00000000000000011e-01_ccs_real, &
        1.30000000000000004e-01_ccs_real, &
        1.00000000000000000e+00_ccs_real, &
        2.99999999999999989e-01_ccs_real, &
        -1.70000000000000012e-01_ccs_real, &
        1.04719755119659785e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        1.04719755119659780e-01_ccs_real, &
        5.23598775598298927e-01_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        1.04719755119659780e-01_ccs_real, &
        6.99999999999999956e-01_ccs_real, &
        -2.00000000000000011e-01_ccs_real, &
        1.30000000000000004e-01_ccs_real, &
        6.99999999999999956e-01_ccs_real, &
        -2.00000000000000011e-01_ccs_real, &
        1.30000000000000004e-01_ccs_real, &
        6.99999999999999956e-01_ccs_real, &
        -2.00000000000000011e-01_ccs_real, &
        1.30000000000000004e-01_ccs_real, &
        1.00000000000000000e+00_ccs_real, &
        2.99999999999999989e-01_ccs_real, &
        -1.70000000000000012e-01_ccs_real, &
        1.04719755119659785e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        1.04719755119659780e-01_ccs_real, &
        5.23598775598298927e-01_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        1.04719755119659780e-01_ccs_real, &
        6.99999999999999956e-01_ccs_real, &
        -2.00000000000000011e-01_ccs_real, &
        1.30000000000000004e-01_ccs_real, &
        6.99999999999999956e-01_ccs_real, &
        -2.00000000000000011e-01_ccs_real, &
        1.30000000000000004e-01_ccs_real, &
        6.99999999999999956e-01_ccs_real, &
        -2.00000000000000011e-01_ccs_real, &
        1.30000000000000004e-01_ccs_real, &
        1.00000000000000000e+00_ccs_real, &
        2.99999999999999989e-01_ccs_real, &
        -1.70000000000000012e-01_ccs_real, &
        1.04719755119659785e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        1.04719755119659780e-01_ccs_real, &
        5.23598775598298927e-01_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        1.04719755119659780e-01_ccs_real, &
        6.99999999999999956e-01_ccs_real, &
        -2.00000000000000011e-01_ccs_real, &
        1.30000000000000004e-01_ccs_real, &
        6.99999999999999956e-01_ccs_real, &
        -2.00000000000000011e-01_ccs_real, &
        1.30000000000000004e-01_ccs_real, &
        6.99999999999999956e-01_ccs_real, &
        -2.00000000000000011e-01_ccs_real, &
        1.30000000000000004e-01_ccs_real, &
        1.06000000000000005e+00_ccs_real, &
        4.00000000000000022e-01_ccs_real, &
        -2.30000000000000010e-01_ccs_real, &
        1.04719755119659785e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        1.04719755119659780e-01_ccs_real, &
        3.23601839787577783e-01_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        1.04719755119659780e-01_ccs_real, &
        6.99999999999999956e-01_ccs_real, &
        -2.00000000000000011e-01_ccs_real, &
        1.30000000000000004e-01_ccs_real, &
        6.99999999999999956e-01_ccs_real, &
        -2.00000000000000011e-01_ccs_real, &
        1.30000000000000004e-01_ccs_real, &
        6.99999999999999956e-01_ccs_real, &
        -2.00000000000000011e-01_ccs_real, &
        1.30000000000000004e-01_ccs_real, &
        1.06000000000000005e+00_ccs_real, &
        4.00000000000000022e-01_ccs_real, &
        -2.30000000000000010e-01_ccs_real, &
        1.04719755119659785e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        1.04719755119659780e-01_ccs_real, &
        3.23601839787577783e-01_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        1.04719755119659780e-01_ccs_real], [3, 2, n_fields, n_cases])
  real(ccs_real), parameter, dimension(3, 2, n_fields, n_cases) :: grad_p &
        = reshape([8.00000000000000044e-01_ccs_real, &
        -4.00000000000000022e-01_ccs_real, &
        1.49999999999999994e-01_ccs_real, &
        8.00000000000000044e-01_ccs_real, &
        -4.00000000000000022e-01_ccs_real, &
        1.49999999999999994e-01_ccs_real, &
        8.00000000000000044e-01_ccs_real, &
        -4.00000000000000022e-01_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        6.99999999999999956e-01_ccs_real, &
        -2.00000000000000011e-01_ccs_real, &
        -1.40000000000000013e-01_ccs_real, &
        4.71238898038468967e-01_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        3.33216220361877480e-01_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        8.00000000000000044e-01_ccs_real, &
        -4.00000000000000022e-01_ccs_real, &
        1.49999999999999994e-01_ccs_real, &
        8.00000000000000044e-01_ccs_real, &
        -4.00000000000000022e-01_ccs_real, &
        1.49999999999999994e-01_ccs_real, &
        8.00000000000000044e-01_ccs_real, &
        -4.00000000000000022e-01_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        6.99999999999999956e-01_ccs_real, &
        -2.00000000000000011e-01_ccs_real, &
        -1.40000000000000013e-01_ccs_real, &
        4.71238898038468967e-01_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        3.33216220361877480e-01_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        8.00000000000000044e-01_ccs_real, &
        -4.00000000000000022e-01_ccs_real, &
        1.49999999999999994e-01_ccs_real, &
        8.00000000000000044e-01_ccs_real, &
        -4.00000000000000022e-01_ccs_real, &
        1.49999999999999994e-01_ccs_real, &
        8.00000000000000044e-01_ccs_real, &
        -4.00000000000000022e-01_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        6.99999999999999956e-01_ccs_real, &
        -2.00000000000000011e-01_ccs_real, &
        -1.40000000000000013e-01_ccs_real, &
        4.71238898038468967e-01_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        3.33216220361877480e-01_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        8.00000000000000044e-01_ccs_real, &
        -4.00000000000000022e-01_ccs_real, &
        1.49999999999999994e-01_ccs_real, &
        8.00000000000000044e-01_ccs_real, &
        -4.00000000000000022e-01_ccs_real, &
        1.49999999999999994e-01_ccs_real, &
        8.00000000000000044e-01_ccs_real, &
        -4.00000000000000022e-01_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        6.80000000000000049e-01_ccs_real, &
        -1.60000000000000003e-01_ccs_real, &
        -1.68000000000000010e-01_ccs_real, &
        4.71238898038468967e-01_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        2.76987274573568532e-01_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        8.00000000000000044e-01_ccs_real, &
        -4.00000000000000022e-01_ccs_real, &
        1.49999999999999994e-01_ccs_real, &
        8.00000000000000044e-01_ccs_real, &
        -4.00000000000000022e-01_ccs_real, &
        1.49999999999999994e-01_ccs_real, &
        8.00000000000000044e-01_ccs_real, &
        -4.00000000000000022e-01_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        6.80000000000000049e-01_ccs_real, &
        -1.60000000000000003e-01_ccs_real, &
        -1.68000000000000010e-01_ccs_real, &
        4.71238898038468967e-01_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        2.76987274573568532e-01_ccs_real, &
        0.00000000000000000e+00_ccs_real, &
        0.00000000000000000e+00_ccs_real], [3, 2, n_fields, n_cases])

end module distorted_refs
